config/routes.rb
Rails.application.routes.draw do
 
  root 'static_pages#dashboard'

  resources :routes
	resources :route_types
	resources :buses
  resources :destinations
  resources :assignments

  get '/assign', to: 'static_pages#assign_route', as: :assign_route
  get '/stats', to: 'stats#index', as: :stats

end

app/controllers/route_types_controller.rb
class RouteTypesController < ApplicationController
  before_action :set_route_type, only: [:show, :edit, :update, :destroy]

  # GET /route_types
  # GET /route_types.json
  def index
    @route_types = RouteType.all
  end

  # GET /route_types/1
  # GET /route_types/1.json
  def show
  end

  # GET /route_types/new
  def new
    @route_type = RouteType.new
  end

  # GET /route_types/1/edit
  def edit
  end

  # POST /route_types
  # POST /route_types.json
  def create
    @route_type = RouteType.new(route_type_params)

    respond_to do |format|
      if @route_type.save
        format.html { redirect_to @route_type, notice: 'Route type was successfully created.' }
        format.json { render :show, status: :created, location: @route_type }
      else
        format.html { render :new }
        format.json { render json: @route_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /route_types/1
  # PATCH/PUT /route_types/1.json
  def update
    respond_to do |format|
      if @route_type.update(route_type_params)
        format.html { redirect_to @route_type, notice: 'Route type was successfully updated.' }
        format.json { render :show, status: :ok, location: @route_type }
      else
        format.html { render :edit }
        format.json { render json: @route_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /route_types/1
  # DELETE /route_types/1.json
  def destroy
    @route_type.destroy
    respond_to do |format|
      format.html { redirect_to route_types_url, notice: 'Route type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route_type
      @route_type = RouteType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_type_params
      params.require(:route_type).permit(:description)
    end
end

app/helpers/route_types_helper.rb
module RouteTypesHelper
end

app/views/route_types/_form.html.erb
<%= simple_form_for(@route_type) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/route_types/edit.html.erb
<h1>Τύπος δρομολόγιου</h1>

<%= render 'form' %>

<%= link_to 'Τύπος Δρομολόγιου', @route_type, class: 'btn btn-primary margin-top-20' %> 
<%= link_to 'Τύποι Δρομολόγιων', route_types_path, class: 'btn btn-primary margin-top-20' %>

app/views/route_types/index.html.erb
<h1>Τύποι δρομολογίων</h1>

<table class="table table-stripped">
  <thead>
    <tr>
      <th>Τύπος</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @route_types.each do |route_type| %>
      <tr>
        <td><%= route_type.description %></td>
        <td>
          <%= link_to 'Τύπος δρομολόγιου', route_type, class: 'btn btn-primary btn-xs' %>
          <%= link_to 'Επεξεργασία', edit_route_type_path(route_type), class: 'btn btn-primary btn-xs' %>
          <%= link_to 'Διαγραφή', route_type, method: :delete, class: 'btn btn-danger btn-xs', data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Νέος τύπος δρομολογίου', new_route_type_path, class: 'btn btn-primary' %>

app/views/route_types/new.html.erb
<h1>Νέος τύπος δρομολογίου</h1>

<%= render 'form' %>

<%= link_to 'Τύποι δρομολογίων', route_types_path, class: 'btn btn-primary margin-top-20'%>

app/views/route_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Τύπος:</strong>
  <%= @route_type.description %>
</p>

<%= link_to 'Επεξεργασία', edit_route_type_path(@route_type), class: 'btn btn-primary margin-top-20' %> 
<%= link_to 'Τύποι Δρομολογίων', route_types_path, class: 'btn btn-primary margin-top-20' %>