config/routes.rb
Rails.application.routes.draw do
 
  root 'static_pages#dashboard'

  resources :routes
	resources :route_types
	resources :buses
  resources :destinations
  resources :assignments

  get '/assign', to: 'static_pages#assign_route', as: :assign_route
  get '/stats', to: 'stats#index', as: :stats

end

app/models/route.rb
class Route < ActiveRecord::Base
  belongs_to :destination
  belongs_to :route_type
  has_many :assignments
  has_many :buses, through: :assignments

  validates :destination_id, :route_type_id, :code_name, :time, :night, presence: true
  validates_numericality_of :night
  validates_time :time

  def human_express
    express ? 'Ναί' : 'Όχι'
	end
end

app/models/route_type.rb
class RouteType < ActiveRecord::Base
	has_many :routes

	validates :description, presence: true
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  # GET /routes
  # GET /routes.json
  def index
    @q = Route.search(params[:q])
    @routes = @q.result(distinct: true).paginate(:page => params[:page])
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(route_params)

    respond_to do |format|
      if @route.save
        format.html { redirect_to @route, notice: 'Route was successfully created.' }
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: 'Route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:code_name, :destination_id, :route_type_id, :time, :night, :express)
    end
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/_form.html.erb
<%= simple_form_for(@route) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :code_name %>
    <%= f.association :destination, label_method: :city, value_method: :id, include_blank: false %>
    <%= f.association :route_type, label_method: :description, value_method: :id, include_blank: false %>
    <%= f.input :time %>
    <%= f.input :night %>
    <%= f.input :express %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1>Δρομολόγιο</h1>

<%= render 'form' %>

<%= link_to 'Δρομολόγιο', @route, class: 'btn btn-primary margin-top-20' %> |
<%= link_to 'Δρομολόγια', routes_path, class: 'btn btn-primary margin-top-20' %>

app/views/routes/index.html.erb
<h1>Δρομολόγια</h1>
<div class="col-md-9">
<table class="table table-stripped">
  <thead>
    <tr>
      <%= content_tag :th, sort_link(@q, :code_name) %>
      <%= content_tag :th, sort_link(@q, :destination_city) %>
      <th>Route type</th>
      <%= content_tag :th, sort_link(@q, :time) %>
      <%= content_tag :th, sort_link(@q, :night) %>
      <%= content_tag :th, sort_link(@q, :express) %>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.code_name %></td>
        <td><%= route.destination.city %></td>
        <td><%= route.route_type.description %></td>
        <td><%= route.time %></td>
        <td><%= route.night %></td>
        <td><%= route.human_express %>
        <td>
          <%= link_to ' Δρομολόγιο', route, class: 'btn btn-primary btn-xs' %>
          <%= link_to 'Επεξεργασία', edit_route_path(route), class: 'btn btn-primary btn-xs' %>
          <%= link_to 'Διαγραφή', route, class: 'btn btn-danger btn-xs', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @routes, renderer: BootstrapPagination::Rails %>
<br>

<%= link_to 'Νέο Δρομολόγιο', new_route_path, class: 'btn btn-primary' %>
</div>
<div class="col-md-3">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Εύρεση</h3>
    </div>
    <div class="panel-body">
      <%= search_form_for @q do |f| %>
        <div class="form-group">
          <label for="code_name">Κωδικός</label>
          <%= f.search_field :code_name_cont, class: 'form-control' %>
        </div>

        <div class="form-group">
          <label for="code_name">Προορισμός</label>
          <%= f.select :destination_id_eq, options_from_collection_for_select(Destination.all, "id", "city"), { include_blank: true }, { class: 'form-control' } %>
        </div>
        
        <%= f.submit class: 'btn btn-primary' %>
        <%= link_to 'Εκκαθάριση', routes_path, class: 'btn btn-danger' %>
      <% end %>
    </div>
  </div>
</div>

app/views/routes/new.html.erb
<h1>Νέο Δρομολόγιο</h1>

<%= render 'form' %>

<%= link_to 'Δρομολόγια', routes_path, class: 'btn btn-primary margin-top-20' %>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Κωδικός:</strong>
  <%= @route.code_name %>
</p>

<p>
  <strong>Προορισμός:</strong>
  <%= @route.destination %>
</p>

<p>
  <strong>Τύπος:</strong>
  <%= @route.route_type %>
</p>

<p>
  <strong>Ώρα:</strong>
  <%= @route.time %>
</p>

<p>
  <strong>Εχπρεσσ:</strong>
  <%= @route.human_express %>
</p>

<%= link_to 'Επεξεργασία', edit_route_path(@route), class: 'btn btn-primary margin-top-20' %> |
<%= link_to 'Δρομολόγια', routes_path, class: 'btn btn-primary margin-top-20' %>