config/routes.rb
Rails.application.routes.draw do
 
  root 'static_pages#dashboard'

  resources :routes
	resources :route_types
	resources :buses
  resources :destinations
  resources :assignments

  get '/assign', to: 'static_pages#assign_route', as: :assign_route
  get '/stats', to: 'stats#index', as: :stats

end

app/models/destination.rb
class Destination < ActiveRecord::Base
	has_many :routes

	validates :city, presence: true
	validates :km_real, :km_plasma, numericality: true

	self.per_page = 15
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json
  def index
    @q = Destination.search(params[:q])
    @destinations = @q.result(distinct: true).paginate(:page => params[:page])
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Ο προορισμός δημιουργήθηκε' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Ο προορισμός ενημερώθηκε' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])

      rescue ActiveRecord::RecordNotFound
      flash[:alert] = "Ο προορισμός δεν υπάρχει"
      redirect_to destinations_path
  
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:city, :km_real, :km_plasma)
    end
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/destinations/_form.html.erb
<%= simple_form_for(@destination) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :city %>
    <%= f.input :km_real %>
    <%= f.input :km_plasma %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<h1>Προορισμός</h1>

<%= render 'form' %>

<%= link_to 'Προορισμός', @destination, class: 'btn btn-primary margin-top-20' %>
<%= link_to 'Προορισμοί', destinations_path, class: 'btn btn-primary margin-top-20' %>

app/views/destinations/index.html.erb
<div class="col-md-9">
<h1>Προορισμοί</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <%= content_tag :th, sort_link(@q, :city) %>
      <%= content_tag :th, sort_link(@q, :km_real) %>
      <%= content_tag :th, sort_link(@q, :km_plasma) %>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @destinations.each do |destination| %>
      <tr>
        <td><%= destination.city %></td>
        <td><%= destination.km_real %></td>
        <td><%= destination.km_plasma %></td>
        <td>
          <%= link_to 'Δρομολόγιο', destination, class: 'btn btn-primary btn-xs' %>
          <%= link_to 'Επεξεργασία', edit_destination_path(destination), class: 'btn btn-primary btn-xs' %>
          <%= link_to 'Διαγραφή', destination, class: 'btn btn-danger btn-xs', method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @destinations, renderer: BootstrapPagination::Rails %>
<br>

<%= link_to 'Νέος Προορισμός', new_destination_path, class: 'btn btn-primary' %>
</div>

<div class="col-md-3">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Εύρεση Πόλης</h3>
    </div>
    <div class="panel-body">
      <%= search_form_for @q do |f| %>
        <div class="form-group">
          <%= f.search_field :city_cont, class: 'form-control' %>
        </div>
        
        <%= f.submit class: 'btn btn-primary' %>
        <%= link_to 'Εκκαθάριση', destinations_path, class: 'btn btn-danger' %>
      <% end %>
    </div>
  </div>
</div>

app/views/destinations/new.html.erb
<h1>Νέος Προορισμός</h1>

<%= render 'form' %>

<%= link_to 'Προορισμοί', destinations_path, class: 'btn btn-primary margin-top-20' %>

app/views/destinations/show.html.erb
<p>
  <strong>Πόλη:</strong>
  <%= @destination.city %>
</p>

<p>
  <strong>Χιλιόμετρα:</strong>
  <%= @destination.km_real %>
</p>

<p>
  <strong>Χιλιόμετρα πλασματικά:</strong>
  <%= @destination.km_plasma %>
</p>

<%= link_to 'Επεξεργασία', edit_destination_path(@destination), class: 'btn btn-primary margin-top-20' %> 
<%= link_to 'Προορισμοί', destinations_path, class: 'btn btn-primary margin-top-20' %>