config/routes.rb
Rails.application.routes.draw do
 
  root 'static_pages#dashboard'

  resources :routes
	resources :route_types
	resources :buses
  resources :destinations
  resources :assignments

  get '/assign', to: 'static_pages#assign_route', as: :assign_route
  get '/stats', to: 'stats#index', as: :stats

end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
  before_action :set_bus, only: [:show, :edit, :update, :destroy]

  # GET /buses
  # GET /buses.json
  def index
    @q = Bus.search(params[:q])
    @buses = @q.result.includes(:destinations, :route_types).paginate(:page => params[:page])
  end

  # GET /buses/1
  # GET /buses/1.json
  def show
  end

  # GET /buses/new
  def new
    @bus = Bus.new
  end

  # GET /buses/1/edit
  def edit
  end

  # POST /buses
  # POST /buses.json
  def create
    @bus = Bus.new(bus_params)

    respond_to do |format|
      if @bus.save
        format.html { redirect_to @bus, notice: 'Bus was successfully created.' }
        format.json { render :show, status: :created, location: @bus }
      else
        format.html { render :new }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buses/1
  # PATCH/PUT /buses/1.json
  def update
    respond_to do |format|
      if @bus.update(bus_params)
        format.html { redirect_to @bus, notice: 'Bus was successfully updated.' }
        format.json { render :show, status: :ok, location: @bus }
      else
        format.html { render :edit }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buses/1
  # DELETE /buses/1.json
  def destroy
    @bus.destroy
    respond_to do |format|
      format.html { redirect_to buses_url, notice: 'Bus was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bus
      @bus = Bus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bus_params
      params.require(:bus).permit(:number, :label)
    end
end

app/helpers/buses_helper.rb
module BusesHelper
end

app/views/buses/_form.html.erb
<%= simple_form_for(@bus) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :number %>
    <%= f.input :label %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/buses/edit.html.erb
<h1>Λεωφορίο</h1>

<%= render 'form' %>

<%= link_to 'Λεωφορίο', @bus, class: 'btn btn-primary margin-top-20' %> |
<%= link_to 'Λεωφορία', buses_path, class: 'btn btn-primary margin-top-20' %>

app/views/buses/index.html.erb
<h1>Λεωφορία</h1>

<table class="table table-stripped">
  <thead>
    <tr>
      <%= content_tag :th, sort_link(@q, :number) %>
      <th>Πινακίδα</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @buses.each do |bus| %>
      <tr>
        <td><%= bus.number %></td>
        <td><%= bus.label %></td>
        <td>
          <%= link_to 'Λεωφορίο', bus, class: 'btn btn-primary btn-xs' %>
          <%= link_to 'Επεξεργασία', edit_bus_path(bus), class: 'btn btn-primary btn-xs' %>
          <%= link_to 'Διαγραφή', bus, class: 'btn btn-danger btn-xs', method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @buses, renderer: BootstrapPagination::Rails %>
<br>
<%= link_to 'Νέο Λεωφορίο', new_bus_path, class: 'btn btn-primary' %>

app/views/buses/new.html.erb
<h1>Προσθήκη Λεωφορίου</h1>

<%= render 'form' %>

<%= link_to 'Λεωφορία', buses_path, class: 'btn btn-primary margin-top-20' %>

app/views/buses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Νούμερο:</strong>
  <%= @bus.number %>
</p>

<p>
  <strong>Πινακίδα:</strong>
  <%= @bus.label %>
</p>

<%= link_to 'Επεξεργασία', edit_bus_path(@bus), class: 'btn btn-primary margin-top-20' %> |
<%= link_to 'Λεωφορία', buses_path, class: 'btn btn-primary margin-top-20' %>